# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  name: Default
  demands:
  - agent.name -equals ubuntuagent

steps:
- script: |
    python3 -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'saikumartest'
    organization: 'saikumartest'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'pythontesting'
    cliProjectName: 'saikumartest'
    cliSources: '.'

- script: |
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'pytest'
 
- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- script: |
    python3 startup.py sdist
  displayName: 'Artifact creation'

- task: TwineAuthenticate@1
  inputs:
    artifactFeed: 'myproject/pydemofeed'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'twine upload -r pydemofeed dist/*'
  displayName: 'publish to azure artifacts'



